### ISSUE TITLE
systemd-unit: check if debug-shell is active or enabled

### ISSUE THREAD

**Issue by bzblf** [Linuxfabrik/monitoring-plugins#642]
### Is your feature request related to a problem? Please describe.

Just a new check. Not related to a existent problem

### Describe the solution you'd like

Check if the systemd service debug-shell.service is active or enabled

**Comment by markuslf** [comment]
By enabling the debug-shell service with `systemctl enable debug-shell.service`, the system spawns a root shell on TTY9 (`Ctrl+Alt+F9`) early during the boot sequence. This shell is automatically logged in as root, so that administrators can debug the system while the operating system is still booting.

The reason for this FR: We don't want to forget to disable the `debug-shell.service` service when we are done debugging, because it leaves an unauthenticated root shell open to anyone with local console access.

**Comment by markuslf** [comment]
Done.
