### ISSUE TITLE
nextcloud-version:  check within a given major version number only

### ISSUE THREAD

**Issue by stephanhendl** [Linuxfabrik/monitoring-plugins#717]
### Describe the solution you'd like

After upgrading to Nextcloud 26.0.6 the check shows a CRITICAL alert that there is new version 27.1.1.0 immediately.

`CRITICAL update available: 27.1.1.0 (channel=stable php=8.2.10)`

Since we don't want to upgrade our productive system to version 27 so early it would be fine to have an option to check within the major version 26 only.

`usage: nextcloud-version [-h] [-V] [--always-ok] [--path PATH] [--version MAJOR-Version]`

**Comment by markuslf** [comment]
Yes, we have thought about that. The release plugins are not perfect yet.

What we would change:
* When a product is EOL, alert. No matter what. That's the golden rule and the current behaviour.
* Add an `--offset-eol` parameter. Usage: `--offset-eol=30`, `--offset-eol=+30` or `--offset-eol=-30`. Means: Alert me when EOL is in 30 days or less (`-30`), or when EOL is already 30 days behind (`+30`), but giving me time to upgrade without being bothered. Default: -30 days.
* Add a `--alert-latest-major' switch: Also alert me when there is a new major release available, even if my current product is not EOL. Only for products with semantic versioning, otherwise print a note that the switch can't be used on non-semantic versions. Example: I get an alert when I run NC 26 (not yet EOL) and NC 27 is available.
* Add a `--alert-latest-minor' switch: I get an alert when I run NC 26.1 (not yet EOL) and NC 26.2 is available.
* Add an `--alert-latest-patch' switch: I get an alert if I run NC 26.1.3 (still not EOL) and NC 26.1.4 is available.
* The switches can be combined.
* Add a `--offset-latest-release-date' switch. Use the same syntax as `--offset-eol`. When using the `--alert-latest-*` switches, alert me x days before or after the latest release date Default: 0 days. Example: NC 27 was released on 2023-06-12, the latest release NC 27.1.1 on 2023-09-21. If I specify `--alert-latest-patch --offset-latest-release-date=5` I get a warning on 2023-09-26 that there is a new release waiting for me.

That could fit all products and use cases.

**Comment by stephanhendl** [comment]
Well, thank you very much. That's what I wanted to achieve. I think I would use a combination of

`--offset-eol=-30 --alert-latest-minor --alert-latest-patch`

One question: I find an `--alert-latest-major` and an `--offset-latest-release` but no `--alert-latest-release`. Are `latest-major` and `latest-release` synonyms?

**Comment by markuslf** [comment]
It will be `--offset-latest-release-date`, not `--offset-latest-release`. In case of Nextcloud (for example), this is as of today
* NC27: 2023-09-21 (for 27.1.1)
* NC26: 2023-09-20 (for 26.0.7)
So this parameter has nothing to do with the "major.minor.patch" semantic versioning scheme.

**Comment by markuslf** [comment]
Now this is what was implemented:

      --check-major         Alert me when there is a new major release available,
                            even if the current version of my product is not EOL.
                            Example: Notify when I run v26 (not yet EOL) and v27
                            is available. Default: False
      --check-minor         Alert me when there is a new major.minor release
                            available, even if the current version of my product
                            is not EOL. Example: Notify when I run v26.2 (not yet
                            EOL) and v26.3 is available. Default: False
      --check-patch         Alert me when there is a new major.minor.patch release
                            available, even if the current version of my product
                            is not EOL. Example: Notify when I run v26.2.7 (not
                            yet EOL) and v26.2.8 is available. Default: False
      --offset-eol OFFSET_EOL
                            Alert me n days before ("-30") or after an EOL date
                            ("30" or "+30"). Default: -30 days

Output (example):

    Nextcloud v22.1.7 (EOL 2022-07-01 -30d [WARNING], major 27.1.2 available, minor 22.2.10 available)
