### ISSUE TITLE
[ntp-w32tm: ] Stratum warning level selector

### ISSUE THREAD

**Issue by reqsyszeroize** [Linuxfabrik/monitoring-plugins#794]
### Describe the solution you'd like

Hello !

I am using this plugin in my organisation and it work very well :D 
But in one of my customers environnement, I have Warnings type alerts because Stratum is equal to 5 even tho its normal in this specific context.

So i would like to know if it could be possible to let the possibility as a argument or parameter to define at wich stratum a warning starts.
I see that right now its hard coded like : 
```
if stratum > 4:
                msg.append('{} {}'.format(line, lib.base.state2str(STATE_WARN)))
                state = STATE_WARN
```
But could we maybe have something like this ? : 
```
    parser.add_argument(
        '-s, '--Stratum',
        help='Set the Stratum level at witch it trigger a warning. '
             'Default: %(default)ss',
        dest='WARN',
        type=int,
        default=4,
    )
```

Let me know what you think about it and thanks for reading me !

**Comment by markuslf** [comment]
The plugin assumes that it has to support boundaries for the Windows Time service (W32Time) in environments that require highly accurate and stable system time. To ensure a target accuracy of at least 50 milliseconds, the target system must be no further than stratum 5 from a highly accurate time source. That's why it is hard-coded.

https://learn.microsoft.com/en-us/troubleshoot/windows-server/active-directory/support-boundary-high-accuracy-time#target-accuracy-50-milliseconds

But actually it wouldn't be that hard to implement such a parameter and setting the default to 5. ;-)

**Comment by reqsyszeroize** [comment]
Thank you for your answer, knowledge and time !
I will investigate this infrastructure in order to see if i can get it to be stratum 4 then.
