### ISSUE TITLE
swap-usage: Windows | Virus detected

### ISSUE THREAD

**Issue by topelrapha** [Linuxfabrik/monitoring-plugins#796]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a setup/configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I use the latest release of the Monitoring Plugins (https://github.com/Linuxfabrik/monitoring-plugins/releases).
- [X] I agree to follow Monitoring Plugins's [Code of Conduct](https://github.com/Linuxfabrik/monitoring-plugins/blob/main/CODE_OF_CONDUCT.md).

### Which variant of the Monitoring Plugins do you use?

- [ ] .rpm/.deb package from repo.linuxfabrik.ch
- [ ] Compiled for Linux (.tar/.zip from download.linuxfabrik.ch)
- [X] Compiled for Windows (from download.linuxfabrik.ch)
- [ ] Source Code from GitHub

### Bug description

Our virus detection engine (Trellix) escalates on christmas holidays and alerts every run of swap-usage check on Windows Server. A file based virus scan removes the swap-usage.exe file from server.

I take a look in virustotal and unfortunately there are actually 10 vendors which flagged this check file as malicious. [(Link to Virtustotal)](https://www.virustotal.com/gui/file/859f987dd44376d9ddd28e0d440d6d8bdd2eddd7392df930f8aa72ace847f5f9/detection) A quick view in respository or included libraries like psutil give me not more information about the reason.

Do you have any idea?

### Steps to reproduce - Plugin call

'C:\ProgramData\icinga2\usr\lib64\nagios\plugins\swap-usage.exe' '--critical' '100' '--warning' '99'

### Environment

Windows Server 2019 - 2022
Trellix ENS

### Plugin Version

swap-usage.exe: v2024033101 by Linuxfabrik GmbH, Zurich/Switzerland

**Comment by markuslf** [comment]
Yes, unfortunately for Windows we get this on a regular basis. Be aware that VirusTotal produces a lot of false positives. Many scanners have a 'better safe than sorry' attitude as security is their business. Some scanners will classify legitimate applications as malicious simply because they access the clipboard or get the desktop statistics.

We have also started to [report false positives](https://docs.virustotal.com/docs/false-positive-contacts), and some of the scanner vendors act very quickly by correcting their scanners, but this has to be done separately for each scanner, for each check-plugin and with every new version.

The best thing would be to get the executables code-signed - something we're working on, currently clarifying how to get a code-signing certificate for open source projects (see https://github.com/Linuxfabrik/monitoring-plugins/issues/791).

Closing this issue.
